server:
  port: 8891
spring:
  application:
    name: server-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csdn?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 771003
    #    schema:
    #      - classpath:ssm.sql
    initialization-mode: always
    # springboot项目加载的时候，自动执行这些脚本文件
    #    druid数据源的相关配置
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.springcloud_server_provider.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka